### ISSUE TITLE
Error when dependency caching is turned on

### ISSUE THREAD

**Issue by komalali** [pulumi/console-requests#480]
A user is reporting that "Enabling [dependency caching] for my deployments just causes them to fail with this error at the cache restore step"

```
Error: failed find cache folder location: exit status 1 
```

Even if we don't support the package manager, we shouldn't fail the deployment. And we should return a clearer error so the user can create an issue for adding a new package manager.

**Comment by jzeiders-silk** [comment]
@komalali 

package.json for the problematic stack

```
{
  "name": "client",
  "main": "index.ts",
  "type": "module",
  "devDependencies": {
    "@types/node": "^22.5.4",
    "prettier": "^3.3.3",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2"
  },
  "engines": {
    "node": "^20.9.0"
  },
  "dependencies": {
    "@pulumi/aws": "^6.55.0",
    "@pulumi/docker": "^4.5.6",
    "@pulumi/kubernetes": "^4.18.1",
    "@pulumi/pulumi": "^3.136.1"
  },
  "packageManager": "yarn@4.5.0"
}
```

**Comment by IaroslavTitov** [comment]
Fixed by https://github.com/pulumi/pulumi-service/pull/24595

**Comment by jzeiders-silk** [comment]
@komalali Appreciate this! Getting a new error now...

```
Restore cache
1.7 seconds
1
 $ /pulumi-deploy-executor cache restore --workDir="/deployment/client/infra" --stackIdentity="silkline/client/development-gov" 
2
 Restoring cache for stack silkline/client/development-gov 
3
 panic: runtime error: index out of range [1] with length 1 
4
  
5
 goroutine 1 [running]: 
6
 github.com/pulumi/pulumi-service/cmd/pulumi-deploy-executor/cmd.getNodeCacheEntries() 
7
 	/src/cmd/pulumi-deploy-executor/cmd/cache_save.go:249 +0xc2b 
8
 github.com/pulumi/pulumi-service/cmd/pulumi-deploy-executor/cmd.getCacheEntriesForRuntime({0xc00067e0e4?, 0x2165bc0?}) 
9
 	/src/cmd/pulumi-deploy-executor/cmd/cache_save.go:187 +0xbb 
10
 github.com/pulumi/pulumi-service/cmd/pulumi-deploy-executor/cmd.init.func2(0xc0005cde00?, {0x12168fa?, 0x4?, 0x12168fe?}) 
11
 	/src/cmd/pulumi-deploy-executor/cmd/cache_restore.go:42 +0xdc 
12
 github.com/spf13/cobra.(*Command).execute(0x20e8780, {0xc00060c700, 0x2, 0x2}) 
13
 	/src/vendor/github.com/spf13/cobra/command.go:985 +0xaca 
14
 github.com/spf13/cobra.(*Command).ExecuteC(0x20ea440) 
15
 	/src/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff 
16
 github.com/spf13/cobra.(*Command).Execute(...) 
17
 	/src/vendor/github.com/spf13/cobra/command.go:1041 
18
 github.com/pulumi/pulumi-service/cmd/pulumi-deploy-executor/cmd.Execute() 
19
 	/src/cmd/pulumi-deploy-executor/cmd/root.go:27 +0x1a 
20
 main.main() 
21
 	/src/cmd/pulumi-deploy-executor/main.go:10 +0xf 
```
